version: '3'
services:
  db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - './db:/var/lib/mysql'
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - 'db:db'
    ports:
      - '8000:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306 
  app:
    build: .
    ports:
      - '80:80'
    volumes:
      - './app:/var/www/html/'
    restart: always
    links:
      - db
    networks:
      - default
volumes:
  persistent: null